"""
First-run setup wizard (Tkinter, 5 steps).

Writes %APPDATA%\\shein-extract\\config.env with the user's choices, marks
first-run complete, and triggers a one-time SHEIN login in the persistent
Chrome profile.

Steps:
  1. Welcome
  2. System check (Chrome + Google Drive for Desktop)
  3. Path config (4 paths: input dir, input file, output dir, backup dir)
  4. SHEIN login (launch Chrome, wait for user to log in & close)
  5. Test (verify Anthropic API key + write test to output dir)
  Final: Done

Returns True if the user completed the wizard, False if cancelled.
"""

import os
import re
import shutil
import subprocess
import sys
import threading
import time
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

import requests

USER_DATA_DIR = Path(os.environ.get("APPDATA", str(Path.home()))) / "shein-extract"
CONFIG_FILE = USER_DATA_DIR / "config.env"
PERSISTENT_PROFILE_DIR = Path(os.path.expanduser("~")) / "shein-cdp-profile"

CHROME_CANDIDATES = [
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    os.path.expandvars(r"%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe"),
]

DRIVE_LETTERS = list("DEFGHIJK")
SHARED_FOLDER_NAME = "共享云端硬盘"
PIPELINE_SUBPATH = Path("02 希音") / "Auto Pipeline"
SUBMITTED_SUBPATH = "Listing - web links (submitted)"
OUTPUT_SUBPATH = "Listing - completed 2nd"


# ── Helpers ──────────────────────────────────────────────────────────────────


def is_first_run_complete() -> bool:
    if not CONFIG_FILE.exists():
        return False
    try:
        text = CONFIG_FILE.read_text(encoding="utf-8")
    except Exception:
        return False
    required = ["SHEIN_SUBMITTED_DIR", "SHEIN_OUTPUT_DIR", "SHEIN_BACKUP_DIR"]
    return all(re.search(rf"^\s*{k}\s*=", text, re.M) for k in required)


def find_chrome() -> str | None:
    for p in CHROME_CANDIDATES:
        if Path(p).exists():
            return p
    return None


def detect_drive_with_shared() -> str | None:
    """Scan likely drive letters for {letter}:\\共享云端硬盘\\02 希音\\Auto Pipeline"""
    for letter in DRIVE_LETTERS:
        candidate = Path(f"{letter}:\\") / SHARED_FOLDER_NAME / PIPELINE_SUBPATH
        if candidate.exists():
            return f"{letter}:"
    return None


def write_config_env(values: dict) -> None:
    USER_DATA_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by SheinExtract setup wizard. Edit by re-running the wizard",
        "# or by deleting this file before launching the app.",
        "",
    ]
    for k, v in values.items():
        lines.append(f"{k}={v}")
    lines.append("")
    CONFIG_FILE.write_text("\n".join(lines), encoding="utf-8")


# ── Wizard ───────────────────────────────────────────────────────────────────


class Wizard:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("SHEIN 上架工具 — 首次设置")
        self.root.geometry("680x520")
        self.root.resizable(False, False)
        try:
            self.root.attributes("-topmost", True)
            self.root.after(500, lambda: self.root.attributes("-topmost", False))
        except Exception:
            pass

        self.completed = False
        self.cancelled = False

        # State that flows between steps
        self.values = {
            "submitted_dir": "",
            "input_filename": "Shein Submited Links.xlsx",
            "output_dir": "",
            "backup_dir": "",
        }
        self.chrome_path = None
        self.detected_drive = None

        # If config.env already exists (re-run via --config), pre-fill the
        # entries with the saved values so the user edits in place.
        self._load_existing_config()

        # Container with consistent padding
        self.frame = ttk.Frame(self.root, padding=20)
        self.frame.pack(fill="both", expand=True)

        self.steps = [
            self._step_welcome,
            self._step_check,
            self._step_paths,
            self._step_login,
            self._step_test,
            self._step_done,
        ]
        self.step_idx = 0
        self._render()

    def _load_existing_config(self) -> None:
        if not CONFIG_FILE.exists():
            return
        try:
            text = CONFIG_FILE.read_text(encoding="utf-8")
        except Exception:
            return
        env_to_state = {
            "SHEIN_SUBMITTED_DIR":  "submitted_dir",
            "SHEIN_INPUT_FILENAME": "input_filename",
            "SHEIN_OUTPUT_DIR":     "output_dir",
            "SHEIN_BACKUP_DIR":     "backup_dir",
        }
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip()
            if k in env_to_state:
                self.values[env_to_state[k]] = v

    # ── frame mgmt ──
    def _clear(self):
        for w in self.frame.winfo_children():
            w.destroy()

    def _render(self):
        self._clear()
        self.steps[self.step_idx]()

    def _next(self):
        if self.step_idx < len(self.steps) - 1:
            self.step_idx += 1
            self._render()

    def _back(self):
        if self.step_idx > 0:
            self.step_idx -= 1
            self._render()

    def _heading(self, text):
        lbl = ttk.Label(self.frame, text=text, font=("Microsoft YaHei", 16, "bold"))
        lbl.pack(anchor="w", pady=(0, 6))
        ttk.Separator(self.frame, orient="horizontal").pack(fill="x", pady=(0, 12))

    def _para(self, text):
        ttk.Label(self.frame, text=text, wraplength=620,
                  justify="left", font=("Microsoft YaHei", 10)).pack(
            anchor="w", pady=(0, 8))

    def _nav_buttons(self, on_next=None, next_text="下一步", show_back=True):
        bar = ttk.Frame(self.frame)
        bar.pack(side="bottom", fill="x", pady=(20, 0))
        ttk.Button(bar, text="取消", command=self._cancel).pack(side="left")
        if show_back and self.step_idx > 0:
            ttk.Button(bar, text="上一步", command=self._back).pack(side="right", padx=4)
        if on_next:
            ttk.Button(bar, text=next_text, command=on_next).pack(side="right", padx=4)

    def _cancel(self):
        if messagebox.askyesno("确认", "现在退出向导，下次启动还需要重新设置。继续吗？"):
            self.cancelled = True
            self.root.destroy()

    # ── Step 1: Welcome ──
    def _step_welcome(self):
        self._heading("欢迎使用 SHEIN 上架工具")
        self._para(
            "这个向导会帮你完成首次设置（约 3-5 分钟）。\n\n"
            "需要确保：\n"
            "  • Google Chrome 已安装\n"
            "  • Google Drive for Desktop 已安装并完成同步\n"
            "  • 你知道 SHEIN 卖家账号的登录信息\n\n"
            "点【开始】继续。"
        )
        self._nav_buttons(on_next=self._next, next_text="开始", show_back=False)

    # ── Step 2: System check ──
    def _step_check(self):
        self._heading("系统检查")

        self.chrome_path = find_chrome()
        self.detected_drive = detect_drive_with_shared()

        chrome_msg = (
            f"✓ 找到 Chrome：{self.chrome_path}"
            if self.chrome_path
            else "✗ 未找到 Chrome —— 请先安装 https://www.google.com/chrome/ 后重新打开向导。"
        )
        drive_msg = (
            f"✓ 检测到共享云端硬盘在 {self.detected_drive}"
            if self.detected_drive
            else "✗ 未在 D~K 盘下找到「共享云端硬盘\\02 希音\\Auto Pipeline」。"
            "\n  请确认 Google Drive for Desktop 已安装并完成同步，或下一步手动指定路径。"
        )

        ttk.Label(self.frame, text=chrome_msg, wraplength=620,
                  justify="left", font=("Microsoft YaHei", 10),
                  foreground="green" if self.chrome_path else "red").pack(
            anchor="w", pady=4)
        ttk.Label(self.frame, text=drive_msg, wraplength=620,
                  justify="left", font=("Microsoft YaHei", 10),
                  foreground="green" if self.detected_drive else "orange").pack(
            anchor="w", pady=4)

        if not self.chrome_path:
            self._para("\n[阻断] 必须先装 Chrome 才能继续。装好之后关闭这个向导再重开。")
            self._nav_buttons(on_next=None, show_back=True)
            return

        if not self.detected_drive:
            self._para(
                "\n如果你确定 Drive 还在装/同步中，可以选择跳过 —— 下一步手动填路径，"
                "等 Drive 就绪后工具自然能跑通。\n"
            )
        self._nav_buttons(on_next=self._next)

    # ── Step 3: Path config ──
    def _step_paths(self):
        self._heading("路径设置")
        self._para(
            "确认或修改以下 4 个路径。如果系统检查时找到了共享盘，路径已自动填写。"
        )

        if self.detected_drive and not self.values["submitted_dir"]:
            base = Path(f"{self.detected_drive}\\") / SHARED_FOLDER_NAME / PIPELINE_SUBPATH
            self.values["submitted_dir"] = str(base / SUBMITTED_SUBPATH)
            self.values["output_dir"] = str(base / OUTPUT_SUBPATH)

        rows = [
            ("输入 Excel 文件夹", "submitted_dir", True),
            ("输入 Excel 文件名", "input_filename", False),
            ("输出根目录", "output_dir", True),
            ("备份目录（建议独立的备份共享盘）", "backup_dir", True),
        ]
        self._entries = {}

        for label, key, browseable in rows:
            row = ttk.Frame(self.frame)
            row.pack(fill="x", pady=4)
            ttk.Label(row, text=label, width=24, anchor="w",
                      font=("Microsoft YaHei", 10)).pack(side="left")
            var = tk.StringVar(value=self.values.get(key, ""))
            entry = ttk.Entry(row, textvariable=var, font=("Consolas", 9))
            entry.pack(side="left", fill="x", expand=True, padx=4)
            self._entries[key] = var
            if browseable:
                ttk.Button(row, text="浏览...",
                           command=lambda v=var: self._browse_dir(v)).pack(side="left")

        def on_next():
            for k, var in self._entries.items():
                self.values[k] = var.get().strip()
            # Validate
            sd = Path(self.values["submitted_dir"])
            if not sd.is_dir():
                messagebox.showerror("路径错误", f"输入文件夹不存在:\n{sd}")
                return
            xlsx = sd / self.values["input_filename"]
            if not xlsx.is_file():
                if not messagebox.askyesno(
                    "文件不存在",
                    f"指定的 Excel 文件不存在:\n{xlsx}\n\n是否仍然继续？"
                    "（员工首次跑之前可以再放进去）",
                ):
                    return
            od = Path(self.values["output_dir"])
            if not od.parent.is_dir():
                messagebox.showerror("路径错误",
                                     f"输出根目录的父目录不存在:\n{od.parent}")
                return
            try:
                od.mkdir(parents=True, exist_ok=True)
            except Exception as e:
                messagebox.showerror("无法创建", f"输出目录创建失败: {e}")
                return
            bd = Path(self.values["backup_dir"])
            if not bd.parent.is_dir():
                if not messagebox.askyesno(
                    "备份目录父目录不存在",
                    f"备份目录的父目录不存在:\n{bd.parent}\n\n仍然继续？",
                ):
                    return
            try:
                bd.mkdir(parents=True, exist_ok=True)
            except Exception as e:
                if not messagebox.askyesno(
                    "无法创建备份目录",
                    f"备份目录创建失败:\n{e}\n\n仍然继续？（运行时再创建）",
                ):
                    return
            self._next()

        self._nav_buttons(on_next=on_next)

    def _browse_dir(self, var: tk.StringVar):
        cur = var.get() or os.path.expanduser("~")
        d = filedialog.askdirectory(initialdir=cur, title="选择文件夹")
        if d:
            var.set(d)

    # ── Step 4: SHEIN login ──
    def _step_login(self):
        self._heading("登录 SHEIN 卖家账号")
        self._para(
            "工具会启动一个专用的 Chrome 窗口（独立 profile，不影响你日常用的 Chrome）。\n\n"
            "请在那个窗口里：\n"
            "  1. 访问 https://us.shein.com 并登录你的卖家账号\n"
            "  2. 登录完成后直接关闭那个 Chrome 窗口\n"
            "  3. 回到这个向导点【已完成登录】\n\n"
            "登录信息会保存在本地 profile 里，以后跑工具不用重新登录。"
        )

        bar = ttk.Frame(self.frame)
        bar.pack(pady=8)
        ttk.Button(bar, text="打开 Chrome 登录 SHEIN",
                   command=self._launch_chrome_for_login).pack(side="left", padx=4)

        self._login_status = ttk.Label(self.frame, text="(尚未启动 Chrome)",
                                       foreground="gray",
                                       font=("Microsoft YaHei", 9))
        self._login_status.pack(pady=4)

        def on_next():
            if not messagebox.askyesno(
                "确认",
                "确定已经在 Chrome 窗口里完成 SHEIN 登录了吗？\n\n"
                "如果还没登，下次跑工具遇到登录拦截会让你手动登。",
            ):
                return
            self._next()

        self._nav_buttons(on_next=on_next, next_text="已完成登录")

    def _launch_chrome_for_login(self):
        if not self.chrome_path:
            messagebox.showerror("Chrome 不可用", "未找到 Chrome 安装。")
            return
        PERSISTENT_PROFILE_DIR.mkdir(parents=True, exist_ok=True)
        try:
            subprocess.Popen([
                self.chrome_path,
                f"--user-data-dir={PERSISTENT_PROFILE_DIR}",
                "--no-first-run",
                "--no-default-browser-check",
                "--disable-blink-features=AutomationControlled",
                "https://us.shein.com",
            ])
            self._login_status.config(
                text="Chrome 已启动 —— 登录后关闭那个窗口，回这里点【已完成登录】",
                foreground="blue",
            )
        except Exception as e:
            messagebox.showerror("启动失败", f"启动 Chrome 失败: {e}")

    # ── Step 5: Test ──
    def _step_test(self):
        self._heading("配置测试")
        self._para(
            "现在做一个轻量测试，确认：\n"
            "  • Anthropic API key 可以正常调用（生成 eBay 标题需要）\n"
            "  • 输出目录可以正常写入\n\n"
            "测试不会调 SHEIN，只验证配置。"
        )

        bar = ttk.Frame(self.frame)
        bar.pack(pady=8)
        self._test_btn = ttk.Button(bar, text="开始测试", command=self._run_test)
        self._test_btn.pack(side="left", padx=4)

        self._test_log = tk.Text(self.frame, height=10, font=("Consolas", 9),
                                 bg="#0f172a", fg="#e2e8f0", state="disabled")
        self._test_log.pack(fill="both", expand=True, pady=8)

        self._test_passed = False

        def on_next():
            if not self._test_passed:
                if not messagebox.askyesno(
                    "测试未通过",
                    "测试还没成功。继续可能在第一次跑工具时报错。\n\n仍然继续？",
                ):
                    return
            self._next()

        self._nav_buttons(on_next=on_next, next_text="完成")

    def _log(self, msg, color=None):
        self._test_log.config(state="normal")
        self._test_log.insert("end", msg + "\n")
        self._test_log.see("end")
        self._test_log.config(state="disabled")
        self.root.update_idletasks()

    def _run_test(self):
        self._test_btn.config(state="disabled")
        self._test_log.config(state="normal")
        self._test_log.delete("1.0", "end")
        self._test_log.config(state="disabled")
        threading.Thread(target=self._test_worker, daemon=True).start()

    def _test_worker(self):
        try:
            self._log("[1/2] 验证 Anthropic API key ...")
            api_key = self._resolve_api_key()
            if not api_key:
                self._log("  ✗ 未找到 API key （bundled key_store 缺失，"
                          ".env 也没填 ANTHROPIC_API_KEY）")
                return
            try:
                resp = requests.post(
                    "https://api.anthropic.com/v1/messages",
                    headers={
                        "x-api-key": api_key,
                        "anthropic-version": "2023-06-01",
                        "content-type": "application/json",
                    },
                    json={
                        "model": "claude-haiku-4-5-20251001",
                        "max_tokens": 16,
                        "messages": [{"role": "user", "content": "ping"}],
                    },
                    timeout=10,
                )
                if resp.status_code == 200:
                    self._log("  ✓ API key 有效")
                else:
                    self._log(f"  ✗ API 调用失败: HTTP {resp.status_code}")
                    self._log(f"    {resp.text[:200]}")
                    return
            except Exception as e:
                self._log(f"  ✗ API 调用异常: {e}")
                return

            self._log("[2/2] 测试输出目录写入权限 ...")
            od = Path(self.values["output_dir"])
            try:
                od.mkdir(parents=True, exist_ok=True)
                test_file = od / ".write_test"
                test_file.write_text("ok", encoding="utf-8")
                test_file.unlink()
                self._log(f"  ✓ {od} 可写")
            except Exception as e:
                self._log(f"  ✗ 写入失败: {e}")
                return

            self._log("\n所有测试通过 ✓")
            self._test_passed = True
        finally:
            self._test_btn.config(state="normal")

    def _resolve_api_key(self) -> str:
        # bundled
        try:
            from key_store import get_obfuscated_key
            k = get_obfuscated_key()
            if k:
                return k
        except ImportError:
            pass
        # .env
        env_path = Path(__file__).resolve().parent / ".env"
        if env_path.exists():
            for line in env_path.read_text(encoding="utf-8").splitlines():
                if line.startswith("ANTHROPIC_API_KEY="):
                    return line.split("=", 1)[1].strip()
        # process env
        return os.environ.get("ANTHROPIC_API_KEY", "")

    # ── Step 6: Done ──
    def _step_done(self):
        self._heading("设置完成")
        self._para(
            "所有配置已保存。以后双击桌面的【SHEIN 上架工具】图标启动。\n\n"
            "首次跑工具时如果遇到验证码 —— Chrome 窗口会显示在你面前，你手动过一下即可。"
            "工具会等你最长 5 分钟。"
        )

        # Persist config now
        write_config_env({
            "SHEIN_SUBMITTED_DIR": self.values["submitted_dir"],
            "SHEIN_INPUT_FILENAME": self.values["input_filename"],
            "SHEIN_OUTPUT_DIR": self.values["output_dir"],
            "SHEIN_BACKUP_DIR": self.values["backup_dir"],
            "SHEIN_FIRSTRUN_COMPLETE": "1",
        })
        self._para(f"配置已保存到：\n  {CONFIG_FILE}")

        bar = ttk.Frame(self.frame)
        bar.pack(side="bottom", fill="x", pady=(20, 0))
        ttk.Button(bar, text="关闭",
                   command=self._finish).pack(side="right", padx=4)

    def _finish(self):
        self.completed = True
        self.root.destroy()

    def run(self) -> bool:
        self.root.mainloop()
        return self.completed and not self.cancelled


def run_wizard() -> bool:
    return Wizard().run()


if __name__ == "__main__":
    ok = run_wizard()
    sys.exit(0 if ok else 1)
